# Generated by Django 6.0.4 on 2026-04-12 06:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intersection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "db_table": "intersection",
            },
        ),
        migrations.CreateModel(
            name="MVTCache",
            fields=[
                ("key", models.CharField(primary_key=True, serialize=False)),
                ("data", models.BinaryField()),
            ],
            options={
                "db_table": "mvt_cache",
            },
        ),
        migrations.CreateModel(
            name="OsmNode",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("is_intersection", models.BooleanField(default=False)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "db_table": "osm_node",
            },
        ),
        migrations.CreateModel(
            name="USPSStreetSuffix",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "name",
                        "alias",
                        "abbreviation",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField()),
                ("alias", models.CharField()),
                ("abbreviation", models.CharField()),
            ],
            options={
                "db_table": "usps_street_suffix",
            },
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("osm_id", models.BigIntegerField()),
                ("osm_seq", models.IntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                ("base_cost", models.FloatField(null=True)),
                ("name", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("highway", models.TextField(null=True)),
                ("bicycle", models.TextField(null=True)),
                ("cycleway", models.TextField(null=True)),
                ("oneway", models.BooleanField(null=True)),
                ("oneway_bicycle", models.BooleanField(null=True)),
                (
                    "end_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_street",
                        to="bycycle_core.intersection",
                    ),
                ),
                (
                    "start_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_street",
                        to="bycycle_core.intersection",
                    ),
                ),
            ],
            options={
                "db_table": "street",
            },
        ),
    ]
